# Generated by Django 4.2 on 2023-11-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_shelter_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seeker',
            name='user_type',
        ),
        migrations.RemoveField(
            model_name='shelter',
            name='user_type',
        ),
        migrations.AddField(
            model_name='parentuser',
            name='user_type',
            field=models.CharField(default='', max_length=6),
        ),
    ]
