# Generated by Django 4.2 on 2023-11-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_parentuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentuser',
            name='profile_picture',
            field=models.ImageField(default='accounts/default_profile.jpg', upload_to='accounts/'),
        ),
    ]
