# Generated by Django 4.2 on 2023-11-13 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_remove_application_pet_id'),
        ('accounts', '0002_seeker_user_type'),
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ADOPTED', 'Adopted')], default='AVAILABLE', max_length=20)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='N/A', max_length=20)),
                ('age', models.IntegerField(default='N/A')),
                ('colour', models.CharField(default='N/A', max_length=20)),
                ('breed', models.CharField(default='N/A', max_length=20)),
                ('location', models.CharField(default='N/A', max_length=30)),
                ('size', models.CharField(choices=[('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large')], default='N/A', max_length=20)),
                ('behaviour', models.CharField(choices=[('FRIENDLY', 'Friendly'), ('SHY', 'Shy'), ('AGGRESSIVE', 'Aggressive')], default='N/A', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('medical_history', models.TextField(blank=True, null=True)),
                ('shelter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.shelter')),
            ],
        ),
        migrations.DeleteModel(
            name='Pet',
        ),
    ]
