# Generated by Django 4.2 on 2023-11-15 03:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petdetail',
            old_name='pet_image1',
            new_name='pet_image_1',
        ),
        migrations.RemoveField(
            model_name='petdetail',
            name='breed',
        ),
        migrations.AddField(
            model_name='petdetail',
            name='deadline',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='petdetail',
            name='type',
            field=models.CharField(choices=[('Cat', 'Cat'), ('Dog', 'Dog'), ('Aquatic', 'Aquatic'), ('Birds', 'Birds')], default=None, max_length=20),
            preserve_default=False,
        ),
    ]
