# Generated by Django 4.2 on 2023-11-14 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_petdetail_delete_pet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petdetail',
            old_name='shelter_id',
            new_name='shelter',
        ),
        migrations.AddField(
            model_name='petdetail',
            name='pet_image1',
            field=models.ImageField(default=None, upload_to='pets/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petdetail',
            name='pet_image2',
            field=models.ImageField(default=None, upload_to='pets/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petdetail',
            name='pet_image3',
            field=models.ImageField(default=None, upload_to='pets/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petdetail',
            name='pet_image4',
            field=models.ImageField(default=None, upload_to='pets/'),
            preserve_default=False,
        ),
    ]
