# Generated by Django 4.2 on 2023-11-15 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('applications', '0002_alter_application_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='adopter',
            field=models.ForeignKey(default='deleted', on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.seeker'),
        ),
        migrations.AlterField(
            model_name='application',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
