# Generated by Django 4.2 on 2023-11-13 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('applications', '0002_application_creation_time'),
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='pet_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pets.pet'),
        ),
        migrations.AlterField(
            model_name='application',
            name='adopter_id',
            field=models.ForeignKey(default='deleted_user', on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.seeker'),
        ),
    ]
