# Generated by Django 4.2 on 2023-11-13 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_application_pet_id_alter_application_adopter_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='pet_id',
        ),
    ]
