# Generated by Django 4.2 on 2023-11-14 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_rename_shelter_id_petdetail_shelter_and_more'),
        ('applications', '0004_remove_application_pet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='pet_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pets.petdetail'),
        ),
    ]
