# Generated by Django 4.2 on 2023-11-14 18:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_rename_shelter_id_petdetail_shelter_and_more'),
        ('applications', '0005_application_pet_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='pet_name',
        ),
        migrations.AlterField(
            model_name='application',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='application',
            name='pet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.petdetail'),
        ),
        migrations.AlterField(
            model_name='application',
            name='street',
            field=models.CharField(max_length=50),
        ),
    ]
